# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/venture/subins_tutorials/studioPipe/test/sample_ui.ui'
#
# Created: Tue Mar 12 22:32:24 2019
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(867, 788)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_main = QtGui.QHBoxLayout()
        self.horizontalLayout_main.setObjectName(_fromUtf8("horizontalLayout_main"))
        self.verticalLayout_sss = QtGui.QVBoxLayout()
        self.verticalLayout_sss.setObjectName(_fromUtf8("verticalLayout_sss"))
        self.horizontalLayout_main.addLayout(self.verticalLayout_sss)
        self.verticalLayout_show = QtGui.QVBoxLayout()
        self.verticalLayout_show.setObjectName(_fromUtf8("verticalLayout_show"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_scrool = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_scrool.setObjectName(_fromUtf8("verticalLayout_scrool"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 199))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout.addWidget(self.pushButton_4, 0, 3, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout.addWidget(self.pushButton_6, 1, 1, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout.addWidget(self.pushButton_7, 1, 2, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.scrollAreaWidgetContents)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout.addWidget(self.pushButton_8, 1, 3, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_scrool.addWidget(self.scrollArea)
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/batman.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsTristate)
        item.setCheckState(QtCore.Qt.Unchecked)
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout_scrool.addWidget(self.listWidget)
        self.verticalLayout_show.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.splitter = QtGui.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget_001 = QtGui.QTreeWidget(self.splitter)
        self.treeWidget_001.setMinimumSize(QtCore.QSize(256, 0))
        self.treeWidget_001.setMaximumSize(QtCore.QSize(256, 16777215))
        self.treeWidget_001.setIconSize(QtCore.QSize(50, 50))
        self.treeWidget_001.setObjectName(_fromUtf8("treeWidget_001"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_001)
        item_0.setIcon(0, icon)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget_001)
        self.treeWidget_2 = QtGui.QTreeWidget(self.splitter)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("1"))
        self.pushButton_10 = QtGui.QPushButton(self.splitter)
        self.pushButton_10.setText(_fromUtf8(""))
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(256, 144))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_show.addWidget(self.groupBox_2)
        self.horizontalLayout_main.addLayout(self.verticalLayout_show)
        self.verticalLayout_4.addLayout(self.horizontalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.action_add_discipline = QtGui.QAction(MainWindow)
        self.action_add_discipline.setObjectName(_fromUtf8("action_add_discipline"))
        self.action_remove_discipline = QtGui.QAction(MainWindow)
        self.action_remove_discipline.setObjectName(_fromUtf8("action_remove_discipline"))
        self.action_add_tag = QtGui.QAction(MainWindow)
        self.action_add_tag.setObjectName(_fromUtf8("action_add_tag"))
        self.action_remove_tag = QtGui.QAction(MainWindow)
        self.action_remove_tag.setObjectName(_fromUtf8("action_remove_tag"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox.setTitle(_translate("MainWindow", "Shows", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("MainWindow", "New Item", None))
        item = self.listWidget.item(1)
        item.setText(_translate("MainWindow", "New Item", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.treeWidget_001.headerItem().setText(0, _translate("MainWindow", "Deciplines", None))
        __sortingEnabled = self.treeWidget_001.isSortingEnabled()
        self.treeWidget_001.setSortingEnabled(False)
        self.treeWidget_001.topLevelItem(0).setText(0, _translate("MainWindow", "Assets", None))
        self.treeWidget_001.topLevelItem(1).setText(0, _translate("MainWindow", "Shots", None))
        self.treeWidget_001.setSortingEnabled(__sortingEnabled)
        self.action_add_discipline.setText(_translate("MainWindow", "Add Decipline", None))
        self.action_remove_discipline.setText(_translate("MainWindow", "Remove Deslipine", None))
        self.action_add_tag.setText(_translate("MainWindow", "Add Tag", None))
        self.action_remove_tag.setText(_translate("MainWindow", "Remove Tags", None))

import qt_rc
