# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/venture/subins_tutorials/studioPipe/test/sample_ui.ui'
#
# Created: Sat Mar 30 23:33:09 2019
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(867, 788)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_main = QtGui.QHBoxLayout()
        self.horizontalLayout_main.setObjectName(_fromUtf8("horizontalLayout_main"))
        self.verticalLayout_sss = QtGui.QVBoxLayout()
        self.verticalLayout_sss.setObjectName(_fromUtf8("verticalLayout_sss"))
        self.horizontalLayout_main.addLayout(self.verticalLayout_sss)
        self.verticalLayout_show = QtGui.QVBoxLayout()
        self.verticalLayout_show.setObjectName(_fromUtf8("verticalLayout_show"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_scrool = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_scrool.setObjectName(_fromUtf8("verticalLayout_scrool"))
        self.scrollArea = QtGui.QScrollArea(self.groupBox)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 829, 199))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.layoutWidget = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget.setGeometry(QtCore.QRect(110, 49, 297, 117))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.layoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_l_add = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_l_add.setFlat(True)
        self.pushButton_l_add.setObjectName(_fromUtf8("pushButton_l_add"))
        self.gridLayout.addWidget(self.pushButton_l_add, 3, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.layoutWidget)
        self.comboBox_2.setEditable(True)
        self.comboBox_2.setInsertPolicy(QtGui.QComboBox.NoInsert)
        self.comboBox_2.setDuplicatesEnabled(False)
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.setItemText(0, _fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.comboBox_2.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 2)
        self.comboBox = QtGui.QComboBox(self.layoutWidget)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout.addWidget(self.comboBox, 1, 1, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setFlat(True)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.lineEdit_add = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_add.sizePolicy().hasHeightForWidth())
        self.lineEdit_add.setSizePolicy(sizePolicy)
        self.lineEdit_add.setObjectName(_fromUtf8("lineEdit_add"))
        self.gridLayout.addWidget(self.lineEdit_add, 3, 2, 1, 1)
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 3, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.layoutWidget)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.layoutWidget1 = QtGui.QWidget(self.scrollAreaWidgetContents)
        self.layoutWidget1.setGeometry(QtCore.QRect(460, 50, 311, 41))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.comboBox_3 = QtGui.QComboBox(self.layoutWidget1)
        self.comboBox_3.setObjectName(_fromUtf8("comboBox_3"))
        self.horizontalLayout_2.addWidget(self.comboBox_3)
        self.label_2 = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_scrool.addWidget(self.scrollArea)
        self.listWidget = QtGui.QListWidget(self.groupBox)
        self.listWidget.setStyleSheet(_fromUtf8("font: 14pt \"Sans Serif\";"))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.verticalLayout_scrool.addWidget(self.listWidget)
        self.verticalLayout_show.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.pushButton_11 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.horizontalLayout.addWidget(self.pushButton_11)
        self.pushButton_9 = QtGui.QPushButton(self.groupBox_3)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout.addWidget(self.pushButton_9)
        self.pushButton = QtGui.QPushButton(self.groupBox_3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.splitter = QtGui.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.treeWidget_001 = QtGui.QTreeWidget(self.splitter)
        self.treeWidget_001.setMinimumSize(QtCore.QSize(256, 0))
        self.treeWidget_001.setMaximumSize(QtCore.QSize(256, 16777215))
        self.treeWidget_001.setLineWidth(10)
        self.treeWidget_001.setAlternatingRowColors(True)
        self.treeWidget_001.setIconSize(QtCore.QSize(50, 50))
        self.treeWidget_001.setIndentation(1)
        self.treeWidget_001.setColumnCount(0)
        self.treeWidget_001.setObjectName(_fromUtf8("treeWidget_001"))
        self.treeWidget_001.header().setDefaultSectionSize(50)
        self.treeWidget_2 = QtGui.QTreeWidget(self.splitter)
        self.treeWidget_2.setObjectName(_fromUtf8("treeWidget_2"))
        self.treeWidget_2.headerItem().setText(0, _fromUtf8("1"))
        self.pushButton_10 = QtGui.QPushButton(self.splitter)
        self.pushButton_10.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/newPrefix/batman.jpg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon)
        self.pushButton_10.setIconSize(QtCore.QSize(256, 144))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_show.addWidget(self.groupBox_2)
        self.horizontalLayout_main.addLayout(self.verticalLayout_show)
        self.verticalLayout_4.addLayout(self.horizontalLayout_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 867, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.action_add_discipline = QtGui.QAction(MainWindow)
        self.action_add_discipline.setObjectName(_fromUtf8("action_add_discipline"))
        self.action_remove_discipline = QtGui.QAction(MainWindow)
        self.action_remove_discipline.setObjectName(_fromUtf8("action_remove_discipline"))
        self.action_add_tag = QtGui.QAction(MainWindow)
        self.action_add_tag.setObjectName(_fromUtf8("action_add_tag"))
        self.action_remove_tag = QtGui.QAction(MainWindow)
        self.action_remove_tag.setObjectName(_fromUtf8("action_remove_tag"))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox.setTitle(_translate("MainWindow", "Shows", None))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_l_add.setText(_translate("MainWindow", "PushButton", None))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Prop", None))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Character", None))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "Environment", None))
        self.comboBox_2.setItemText(4, _translate("MainWindow", "Camera", None))
        self.comboBox_2.setItemText(5, _translate("MainWindow", "Light", None))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton", None))
        self.label_2.setText(_translate("MainWindow", "TextLabel", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox", None))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton", None))
        self.pushButton.setText(_translate("MainWindow", "PushButton", None))
        self.action_add_discipline.setText(_translate("MainWindow", "Add Decipline", None))
        self.action_remove_discipline.setText(_translate("MainWindow", "Remove Deslipine", None))
        self.action_add_tag.setText(_translate("MainWindow", "Add Tag", None))
        self.action_remove_tag.setText(_translate("MainWindow", "Remove Tags", None))

import qt_rc
