string $polyList[]     = `listTransforms "-type mesh"` ;

if (`objExists "GeomertySet"`)
    {
        print "\nWarnning -  Set is allready exist in the name of \"GeomertySet\"\n" ;
    }
else 
    {
        string $set            = `sets -n "GeomertySet" $polyList` ;
        print ("\nSet name\t- \"" + $set + "\"\n") ;
        //print ("\t" + $polyList) ;
        print ("\t" + stringArrayToString ($polyList, "\n\t"));        
        print "\nDone\n" ;
    }
print "\n\n" ;